version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GitHub_API
    ports:
      - "8880:8880"
    command: ["/githubAPI/main"]
    environment:
      TOKEN: ${TOKEN}
    healthcheck:
      test: curl --fail -s http://localhost:8880/followers/hauptj || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

